trigger:
- master

pr:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  displayName: "Restore"
  inputs:
    command: 'restore'
    projects: 'AspNetMigrator.sln'

- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration)'
    projects: 'AspNetMigrator.sln'

- task: DotNetCoreCLI@2
  displayName: "Test"
  inputs:
    command: 'test'
    arguments: '-c $(buildConfiguration)'
    projects: 'AspNetMigrator.sln'