trigger:
- master

pr:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  displayName: 'Install GitVersion'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global GitVersion.Tool'

- task: DotNetCoreCLI@2
  displayName: 'Update Version'
  inputs:
    command: 'custom'
    custom: 'gitversion'
    arguments: '/output buildserver /nofetch'

- task: DotNetCoreCLI@2
  displayName: "Restore"
  inputs:
    command: 'restore'
    projects: 'AspNetMigrator.sln'

- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration)'
    projects: 'AspNetMigrator.sln'

- task: DotNetCoreCLI@2
  displayName: "Test"
  inputs:
    command: 'test'
    arguments: '-c $(buildConfiguration)'
    projects: 'AspNetMigrator.sln'

- task: DotNetCoreCLI@2
  displayName: Create tool package
  inputs:
    command: 'pack'
    packagesToPack: 'src/AspNetMigrator.Console/AspNetMigrator.ConsoleApp.csproj'
    arguments: '-c $(buildConfiguration)'
    packDirectory: '$(Build.ArtifactStagingDirectory)/tools'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: Create analyzer package
  inputs:
    command: 'pack'
    packagesToPack: 'src/Analyzers/AspNetMigrator.Analyzers.Package/AspNetMigrator.Analyzers.Package.csproj'
    arguments: '-c $(buildConfiguration)'
    packDirectory: '$(Build.ArtifactStagingDirectory)/tools'
    versioningScheme: 'off'    

- task: PublishPipelineArtifact@1
  displayName: Publish packages
  inputs:
    targetPath: '$(build.artifactStagingDirectory)/tools'
    artifact: 'tools'
    publishLocation: 'pipeline'

- powershell: |
    dotnet tool install -g sleet
    sleet push $(Build.ArtifactStagingDirectory)/tools --skip-existing
  displayName: Push nuget package to Azure storage
  env:
      SLEET_FEED_TYPE: azure
      SLEET_FEED_CONTAINER: feed
      SLEET_FEED_CONNECTIONSTRING: $(SLEET_CONNECTIONSTRING)
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
